/**
 * Geometry for a comb built the way a comb is: small hexagons of cells, set
 * slightly apart, arranged into a hexagon themselves.
 *
 * Kept apart from the component because it is pure arithmetic, and it is the
 * only part that can be wrong in a way a screenshot would not show.
 *
 * Everything is measured in cell widths, with the origin at the middle of the
 * comb. The component turns that into percentages once, at the end.
 */

/** A pointy-top hexagon is √3/2 as wide as it is tall. */
export const CELL_H = 2 / Math.sqrt(3);
/** A honeycomb stacks its rows three quarters of a cell height apart. */
const ROW_RISE = 0.75 * CELL_H;

/** Cells per cluster: 19, the hexagon three cells to a side. */
export const CLUSTER_SIDE = 3;

/**
 * A nineteen-cell hexagon tiles the plane, because 19 = 2² + 2·3 + 3². The
 * clusters repeat on the sub-lattice generated by the hex vector (2,3) and its
 * sixtieth turn, (-3,5), which has determinant 19: exactly one cluster per
 * nineteen cells, no gaps and no overlaps.
 *
 * This is what makes clusters interlock. Laying them out on a plain
 * rows-and-columns pitch instead leaves each one an island, because a hexagon
 * has notches its neighbours have to nest into and a rectangular pitch never
 * lines them up.
 */
export const LATTICE = [
  [2, 3],
  [-3, 5],
];

/** Mortar between clusters, in cell widths. Cluster centres are √19 apart on
    the tiling lattice, so pushing them out by this fraction of that opens an
    even seam everywhere without breaking the interlock. */
const SEAM = 0.2;
/** Length of a hex vector: |(q,r)|² = q² + qr + r². */
const hexNorm = ([q, r]) => Math.sqrt(q * q + q * r + r * r);
const SPREAD = 1 + SEAM / hexNorm(LATTICE[0]);

/** Cells in a hexagon `side` cells to an edge: 1, 7, 19, 37, 61, 91, 127… */
export const capacity = (side) => 3 * side * side - 3 * side + 1;

/** The smallest hexagon that holds `count` cells. */
export function sideFor(count) {
  let side = 1;
  while (capacity(side) < count) side++;
  return side;
}

/** Row lengths, widest in the middle: side, side+1, … 2·side-1, … side. */
export const hexRows = (side) =>
  Array.from({ length: 2 * side - 1 }, (_, i) => (i < side ? side + i : 3 * side - 2 - i));

/**
 * How many cells a given cell sits from the centre of its hexagon.
 *
 * Row and column are the offset-row coordinates the rows are built in; they
 * convert to cube coordinates, where distance from the origin is half the sum
 * of the absolute components.
 */
export function axialOf(side, row, col) {
  const r = row - (side - 1);
  return [-(side - 1) - Math.min(r, 0) + col, r];
}

export function ring(side, row, col) {
  const [q, r] = axialOf(side, row, col);
  return (Math.abs(q) + Math.abs(q + r) + Math.abs(r)) / 2;
}

/**
 * Every cell of a hexagon, in the order it should be filled: rings from the
 * centre out, and around each ring by angle.
 *
 * A count almost never lands exactly on a hexagonal number, so the last ring
 * is usually part-full. Going by ring keeps the spare cells on the rim rather
 * than hollowing out whole rows, and going by angle within the ring leaves
 * them as one contiguous arc rather than a cell stranded on its own.
 *
 * Both scales use this: cells within a cluster, and clusters within the comb.
 */
export function orderedCells(side) {
  const cells = [];
  hexRows(side).forEach((length, row) => {
    for (let col = 0; col < length; col++) {
      const angle = Math.atan2((row - (side - 1)) * ROW_RISE, col - (length - 1) / 2);
      cells.push({
        row,
        col,
        r: ring(side, row, col),
        // Walk each ring from the top rather than from the left. Both keep the
        // part-full ring in one contiguous piece, which is what stops anything
        // being stranded on its own; starting at the top is what centres the
        // leftover over the rest instead of hanging it off one flank.
        turn: (angle + Math.PI / 2 + 2 * Math.PI) % (2 * Math.PI),
      });
    }
  });
  return cells.sort((a, b) => a.r - b.r || a.turn - b.turn);
}

/** Centre of cell `col` in a centred row of `length`, relative to the hexagon. */
const offsetX = (col, length) => col - (length - 1) / 2;
const offsetY = (row, side) => (row - (side - 1)) * ROW_RISE;

/** Cartesian position of an axial hex coordinate, in cell widths. */
const cartesian = (q, r) => [q + r / 2, r * ROW_RISE];

/** Every cell of one cluster, as an offset from the cluster's own centre. */
const CLUSTER_CELLS = hexRows(CLUSTER_SIDE).flatMap((length, row) =>
  Array.from({ length }, (_, col) => [offsetX(col, length), offsetY(row, CLUSTER_SIDE)])
);

/**
 * Where every word's cell sits, and how big the whole comb is.
 *
 * Returns positions in cell widths with the top-left of the comb at the
 * origin, so the caller only has to divide by `width` and `height`.
 */
export function combLayout(count) {
  const per = capacity(CLUSTER_SIDE);
  const clusterCount = Math.ceil(count / per);
  const gridSide = sideFor(clusterCount);

  const cells = [];
  orderedCells(gridSide)
    .slice(0, clusterCount)
    .forEach((cluster, c) => {
      // Step across the tiling lattice, then push out by the seam. The
      // clusters keep their interlocking arrangement and simply stop touching.
      const [gq, gr] = axialOf(gridSide, cluster.row, cluster.col);
      const [cx, cy] = cartesian(
        (gq * LATTICE[0][0] + gr * LATTICE[1][0]) * SPREAD,
        (gq * LATTICE[0][1] + gr * LATTICE[1][1]) * SPREAD
      );

      // A part-full cluster fills from the side facing the middle of the comb,
      // not from its own centre. Filling from its own centre leaves a nearly
      // empty cluster as a single cell stranded two cells clear of anything
      // else, which is the island this layout exists to avoid. The full
      // clusters take all nineteen either way, so only the last one notices.
      CLUSTER_CELLS.map(([dx, dy]) => ({ x: cx + dx, y: cy + dy }))
        .sort((a, b) => Math.hypot(a.x, a.y) - Math.hypot(b.x, b.y))
        .slice(0, count - c * per)
        .forEach((cell, i) => cells.push({ index: c * per + i, ...cell }));
    });

  const left = Math.min(...cells.map((c) => c.x)) - 0.5;
  const top = Math.min(...cells.map((c) => c.y)) - CELL_H / 2;
  const width = Math.max(...cells.map((c) => c.x)) + 0.5 - left;
  const height = Math.max(...cells.map((c) => c.y)) + CELL_H / 2 - top;

  return {
    width,
    height,
    cells: cells.map((c) => ({ index: c.index, x: c.x - left, y: c.y - top })),
  };
}
